# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cd2017930410d9a8a30293a1308140c008ff86539f1cb84989352f45f72b9d70465cb87109309ac9ddfbae60853f6200b651f1521e307aef57509ea95495c29e

test:
  secret_key_base: 5621c1d937bf065d3c084078dcaf836cdb86bbd9890933c48d83db8e9b8f4985c7c9e9f90fdbacf26bb53da8c62dd6746038bcba80acc5ddd2235861c0185f63

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
